services:
  flask_app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "5000:5000"
    env_file:
      - ../src/.env
    volumes:
      - ../media:/app/src/media
      - ../data:/app/data
      - ../scripts:/app/scripts
    restart: always
